### ISSUE TITLE
Multiple schemas in PostgreSQL

### ISSUE THREAD

**Issue by milo** [nette/nette#1101]
PostgreSQL supports schemas (it is like namespaces in PHP). Main reason for their usage is to split logical parts of database. Example:
```sql
CREATE SCHEMA "admin";
CREATE TABLE "admin.users" (...);

CREATE SCHEMA "shop";
CREATE TABLE "shop.baskets" (...);

-- And now you can do
SELECT * FROM "admin"."users";
SELECT * FROM "shop"."baskets";
-- or
SET search_path TO "admin", "shop";
SELECT * FROM "users";
SELECT * FROM "baskets";
```

Table from one schema can be connected by foreign key to table from second schema. Current `PgSqlDriver` reflection does not support multiple schemas, it uses only current_schema().

If user use only one schema in whole application, there is no problem. Just after connection must do:
```sql
SET search_path TO "schema1"
```

If user use multiple schemas, but all tables are unique named, <del>there is a hot-fixed driver (376ae673fe20297abcf48eefd39b664b5765a070)</del>(already merged) and after connection user must do:
```sql
SET search_path TO "schema1", "schema2", "schema3";
```

A problem comes when table names are not uniq across schemas. Eg:
```
admin.user
shop.user
```
To support this, there are issues to deal with it.
```php
/* CREATE SCHEMA admin; */
/* CREATE TABLE admin.users; */

# If search_path is not set (or default 'public' is used)
$row = $connection->table('users'); # This table does not exists
$row = $connection->table('admin.users'); # OK

# If search_path is set to 'admin'
$row = $connection->table('users'); # OK
$row = $connection->table('admin.users'); # OK
```

**Comment by dg** [comment]
If this issue is still valid, please open it again in https://github.com/nette/database
