### ISSUE TITLE
Latte: new macro useNamespace

### ISSUE THREAD

**Issue by hrach** [nette/nette#1121]
I need to use some constants in my latte template. Something like
```html
{if $item->postOn === Post::ON_USER_PROFILE}
{/if}
```

For that would be really useful to make some use statement imports. 
```
{? use Signaly\Posts\Post}
```
But this is insufficient because it get rendered after snippet blocks. If you need that class in snippet, you are out. Solution would be write own macro {useNamespace} and use finalize method. I did that, but again, $plologs are appanded to previous prologs, so my use statement is after snippet. If this macro would be in core, it could get rendered before snippets.

What do you think?

**Comment by janedbal** [comment]
@hrach It has been closed because [template was wrapped to class](https://github.com/nette/latte/commit/cc72d91b6e66362ba4d527a7b4bbbea04b1bdc26)? Or just nobody cares about this functionality?

**Comment by hrach** [comment]
It has been because:
- I have no intention to fix this PR (rebase, etc)
- David's human timeout
- possbile partial workaround in php 5.4?: `{if $item->postOn === $item::ON_USER_PROFILE}{/if}`, which I personally use.
