### ISSUE TITLE
Database: DateTime's time zone should be normalized before saving

### ISSUE THREAD

**Issue by paranoiq** [nette/nette#1168]
if a DateTime has different time zone, it should be normalized to the time zone of server

there may be databases, which are capable of saving a datetime with timezone, so i am not sure yet, if the normalization shold occur in SqlPreprocessor or in a Driver

(see also: https://github.com/dg/dibi/issues/100)

**Comment by dg** [comment]
If this issue is still valid, please open it again in https://github.com/nette/database
