### ISSUE TITLE
Nette/Database: Where should accept array even with one parameter required

### ISSUE THREAD

**Issue by deep9** [nette/nette#1243]
Since there is no easy way of building where with or from variable number of conditions, it should be possible to easily achieve this:
```php
$parameters = array('...');
$likeArray = array();
foreach ($parameters as $param) {
    $likeArray[] = 'column LIKE ?';
}
$this->connection->table('table')->select('...')->where(implode(' OR ', $likeArray), $parameters);
```
But the above code does not work when $parameters has only one item. The solution to this is easy:
```php
$this->connection->table('table')->select('...')->where(implode(' OR ', $likeArray), count($parameters)>1?$parameters:$parameters[0]);
```
But I think this might be done in the sqlBuilder itself, for consistency.

If there is no real reason for this beahvior, I'll try to make a fix to this later.

**Comment by dg** [comment]
If this issue is still valid, please open it again in https://github.com/nette/database
