### ISSUE TITLE
Route: masks with absolute path and port are not matched correctly

### ISSUE THREAD

**Issue by Majkl578** [nette/nette#1268]
When the route is defined absolutely, with host, and port is specified, the route fails to match and port is ignored. The main (but maybe not the only) problem seems to be [in Route::match()](https://github.com/nette/nette/blob/89e2eaef206e0625e74c8089c6382236e0b74849/Nette/Application/Routers/Route.php#L153-154) method which completely ignores ports.

For more info, see the [forum thread](http://forum.nette.org/cs/15820-route-secured-a-jiny-port).

**Comment by dg** [comment]
If this issue is still valid, please open it again (or fix it) in https://github.com/nette/application
