### ISSUE TITLE
Diagnostics\Logger: custom priorities and sending e-mails

### ISSUE THREAD

**Issue by Majkl578** [nette/nette#1284]
There are now hardcoded e-mails for priorities "error" and "critical" and when user uses his own priority (which is not an uncommon case), there is no way to specify whether mail should be sent or not.

**Comment by dg** [comment]
@Majkl578  is it still valid?

**Comment by Majkl578** [comment]
Yes: https://github.com/nette/tracy/blob/00083f35e542266221a475ed4b48c620890abbec/src/Tracy/Logger.php#L67
I don't know what would be ideal solution since priorities are strings (I was thinking about bitmasks which is not possible).

**Comment by dg** [comment]
Will you send PR?

**Comment by Majkl578** [comment]
This is still valid I believe.

**Comment by dg** [comment]
Nobody cares, so it is needless.
