### ISSUE TITLE
Nette\Database\Row vs Nette\Database\Table\ActiveRow

### ISSUE THREAD

**Issue by insekticid** [nette/nette#1339]
1) rozdilny zpusob ziskavani hodnot sloupcu
2) rozdilne pretypovani na array
3) Nefunkcni $db->query($sql)->rewind() 

ad 1) 
a)
Row umi $row[0] i $row['id'] zatimco ActiveRow umi jen $row['id']
Row::offsetGet($key) ma totiz navic
if (is_int($key)) {
$arr = array_slice((array) $this, $key, 1);

b) vzhledem k tomu ze Row je extends stdClass umi i pristup $this->$key;

ActiveRow tedy neumi $this->$key; ani pristup pomoci nestringoveho indexu aka ActiveRow[0], coz by melo byt ekvivalentni k ActiveRow['id'] za predpokladu ze prvni sloupec ma jmeno id ;)

ad 2) ActiveRow ma metodu toArray(), kterou by mohl mit i Row prestoze ho staci pretypovat pomoci (array)$row

ad 3) staci pridat do ResultSet::rewind()
$this->pdoStatement->fetch(PDO::FETCH_ASSOC, PDO::FETCH_ORI_ABS, 0);

**Comment by dg** [comment]
If this issue is still valid, please open it again in https://github.com/nette/database
