### ISSUE TITLE
Repeating SQL query when loading ref data

### ISSUE THREAD

**Issue by miso-belica** [nette/nette#1367]
Hi, 
I use the code below to generate array of categories and it executes the same query 35 times. Am I doing something wrong? I think that it should be cached and query should execute only once. [Database schema and data](http://pastebin.com/AtrV4N3j).

```php
	public function findAll() {
		$categories = array();
		foreach($this->db->table('categories') as $id => $category) {
			$parentCategory = $category->parent;
			$parentName = ($parentCategory !== NULL)? "{$parentCategory->name} > " : "";
			$categories[$id] = "$parentName{$category->name}";
		}

		return $categories;
	}
```

Repeating query:
```sql
SELECT `id`, `name` 
FROM `categories` 
WHERE (`id` IN (2401, 2501, 801, 1201, 701, 901, 1, 201, 501, 1701, 1801, 
2101, 301, 2201, 2301, 2701, 3301, 3201, 1401, 1601, 2601, 601, 3001, 
1501, 1301, 2001, 1101, 2801, 1901, 101, 1001, 401, 3101, 2901))
```

I'm not sure but I think it's related to the #936. It was fixed but then the fix was removed in [this commit](https://github.com/nette/nette/commit/80a8111c47222bf8580ab7edf8d57f53d44496f5#diff-25d74a66695b4f9cb0747c9a4125e2a7L847)?

**Comment by dg** [comment]
If this issue is still valid, please open it again in https://github.com/nette/
