### ISSUE TITLE
NE-ON: multiline string support

### ISSUE THREAD

**Issue by ViliamKopecky** [nette/nette#1375]
I tried to make a pull-request, but got lost in the `Tokenizer` insides.

I propose using the python multiline string syntax.

From NE-ON:
```python
"""
this
is
"multiline"
'string'
"""
```

To PHP:
```php
"this\nis\n\"multiline\"\n'string'"
```

**Comment by TomasVotruba** [comment]
What is the multiline syntax apart using `\n' then?

**Comment by JanTvrdik** [comment]
https://github.com/nette/neon/blob/master/tests/Neon/Decoder.multiline.phpt

**Comment by TomasVotruba** [comment]
I've read that and found only one liners. I'm looking for multiline string.

**Comment by JanTvrdik** [comment]
What can I say, read it again.

**Comment by TomasVotruba** [comment]
I'm trying to write something with no success:

```neon
key:
    multi
    line
    value
```

**Comment by JanTvrdik** [comment]
Let me be more specific

* https://github.com/nette/neon/blob/437defe8601611325c58c8afc0e159c24b7bceb9/tests/Neon/Decoder.multiline.phpt#L137-L140
* https://ne-on.org/

**Comment by TomasVotruba** [comment]
Thanks, much better!

I expected that in the begging, since that's the real issue.
