### ISSUE TITLE
"Table does not have a primary key" in templates

### ISSUE THREAD

**Issue by aikencz** [nette/nette#1393]
Nette 2.0.11 embodies the following behavior:

When processing a new or modified Latte template, it throws a LogicException with "Table does not have a primary key". It appears multiple times for different database attributes (after reloading). After "sufficient" number of reloads it works correctly and it persists to the next modification of the template.

Older versions of Nette have similar behavior but with different messages.

**Comment by temistokles** [comment]
This issue is still present and seems to be distributed randomly. It is more commonly associated with views, but not exclusive.
The issue usually disappears once the case is created and reappears when cache is deleted.

**Comment by zizkam** [comment]
Any plans to reopen this issue and actually fix it? I am facing this issue with MSSQL View. Each time the cache is deleted, the any first access to a column from the view yields this error. After many reloads of the page (each ends with the same error for the next column) I am able to load the page until next cache reset...

**Comment by dg** [comment]
I leave it up to the community to resolve this issue. I will gladly accept PR.

**Comment by jaromirzajicek** [comment]
Please the problem still persists in the current version :-(
Refers to View on MSSQL. When will the apartment be about to be repaired?

**Comment by dg** [comment]
When someone sends a correction. I'll merge it quickly.

**Comment by zizkam** [comment]
Well, as it is abandoned for such a long time, I am afraid that there is noone who is able to find that problem and correct it. I have "corrected" this issue by using custom DiscoveredConventions which returns the name of the key for each MSSQL View.

**Comment by jaromirzajicek** [comment]
Sorry, the latest version of Latte works correctly

**Comment by jaromirzajicek** [comment]
> DiscoveredConventions

Mužete mi prosím poslat/nastínit  jak máte opraveno?

**Comment by zizkam** [comment]
No ono to právě není opraveno. Je to jenom hack - mám třídu, která dědí od DiscoveredConventions (ani nevím, jestli je to vhodné řešení, ale jelikož jsem používal DiscoveredConventions, bylo to nejjednodušší) a v metodě getPrimary podle názvu tabulky (respektive je to potřeba pouze pro View, s tabulkami to problém nemá) vracím název primárního klíče. Tzn. v moment, kdy do databáze přidám nový pohled, je nutné tohle ručně doplnit :-(

**Comment by milo** [comment]
From my brief overview, there are two problems:

1) The `Structure` does not analyze primary keys on views https://github.com/nette/database/blob/5dd552b0ad8ea6b9019433be8809475ba7d46711/src/Database/Structure.php#L200 Removing the condition looks to be harmless.

2) The `SqlsrvDriver` does not return `primary` flag. It is not possible (I don't know any simple way) to detect it on view's column. There are no such flags in `sys.columns` and similar system views. But in case the primary column is an identity, it could be possible to assume that such column with identity flag in view is a view's primary key. But it should not be, it is an assumption only. Similar change should be done in https://github.com/nette/database/blob/5dd552b0ad8ea6b9019433be8809475ba7d46711/src/Database/Drivers/SqlsrvDriver.php#L119-L122

```sql
CASE WHEN (o.type = 'U' AND i.index_id IS NOT NULL) OR (o.type = 'V' AND c.is_identity = 1)
	THEN 1
	ELSE 0
END AS [primary]
```

And maybe I'm completely wrong.

**Comment by jaromirzajicek** [comment]
díky za nápady panové !
