### ISSUE TITLE
Exception during Json::encode

### ISSUE THREAD

**Issue by PetrP** [nette/nette#1426]
If there is exception during Nette\Utils\Json::encode, whitch can be done for example by JsonSerializable. Then [error handler in Json::encode](https://github.com/nette/nette/blob/master/Nette/Utils/Json.php#L56) is still enabled and throws Nette\Utils\JsonException on next error.
Maybe try-catch in Json::encode with restore_error_handler is enough, but interesting is that it only happens if Debugger is enabled.

Tested on
- Nette v2.0.12 and v2.2-dev released on 2014-02-12
- PHP 5.4 and 5.5

```php
class TestJsonSerializable implements JsonSerializable
{
	public function jsonSerialize()
	{
		throw new Exception;
	}
}
Nette\Diagnostics\Debugger::enable(false);
try {
	Nette\Utils\Json::encode(new TestJsonSerializable);
} catch (Exception $e) {}
@trigger_error('test');
```

Expected result:
none

Actual result:
Nette\Utils\JsonException: test

**Comment by dg** [comment]
Human timeout

**Comment by PetrP** [comment]
Nevím z čeho usuzujete že bych to měl opravovat. Jen jsem vám reportoval bug. Ten "human timeout" je na vaší straně.
Beru to že to pro váš není problém. Příště si rovnou ušetřím čas.

**Comment by dg** [comment]
My si vykáme?

**Comment by fprochazka** [comment]
I think this actually shouldn't have been closed. Through "human timeout" was funny :)

**Comment by dg** [comment]
Dost možná je to opravené.

**Comment by fprochazka** [comment]
Then somebody should write a test case :)

**Comment by dg** [comment]
Sad story

**Comment by PetrP** [comment]
Nebylo to adresováno jen tobě Davide, ale "lidem za Nette". Tvoje reakce mě trochu naštvala, takže během psaní jsem měl trochu rudo před očima. Což není nejlepší stav psát cokoli.

I have no idea if this is fixed. I don't use latest versions of nette.
But I think this can't be fixed just by try-catch in `Json::encode`, as jsonSerialize can trigger only e.g. E_USER_NOTICE, and you don't want then it to fail.

**Comment by enumag** [comment]
@PetrP It's probably fixed because `Callback::invokeSafe()` is used now.

**Comment by dg** [comment]
„Lidi za Nette“ jsem já, nikdy jiný issues neřeší. Což mi sebralo chuť je taky  řešit, takže pokud mě issue nějak nezaujme nebo se mě přímo netýká, tak na to prdím. Pokud ani autor issue nereaguje, tak to asi není důležité. Reporty, které dlouho nikoho netrápí, postupně smažu.

**Comment by PetrP** [comment]
@enumag It may be. Can you check it with "test" in first message? And maybe save it as test case?
I don't have working nette testing environment and I don't know nette testing standards. (Also I'm lazy and looking for excuses.)
For someone who have/know this stuff, it should be very easy.

@dg Uvědomuji si že je jednoduché to kritizovat když se toho neúčastním. Ale já jsem issues řešil tím že jsem ho založil. Myslím že jsem ho i zareportoval kvalitně.
Od tebe jsem na to nedostal žádné vyjádření na které bych mohl dál reagovat.
Jediné co bych mohl udělat je sám ho vyřešit a doufat že pak ho budeš se mnou řešit.

**Comment by dg** [comment]
Druhý den ti Honza napsal otázku, na kterou jsi nereagoval, ani když jsem tě o pár měsíců později pošťouchl. Fakt vevím, jak jsem se k tomu měl vyjadřovat.

**Comment by enumag** [comment]
@PetrP I don't have time for it right now.

**Comment by PetrP** [comment]
@enumag Don't worry about it.

@dg Ano, měl jsem na to honzovi odpovědět. A měl jsem i zkusit poslat pull request. Svět by byl lepší když by to tak všichni dělali a podněcovali takové chování.

**Comment by dg** [comment]
ok :-)
