### ISSUE TITLE
table()->insert on Postgre Table without sequence reads invalid id

### ISSUE THREAD

**Issue by mistercz** [nette/nette#1454]
1) Insert of the row is successful
2) Searching for sequence end with null
3) Calling getInsertId(null)
4) gePdo->lastInsertId(null) returns wrong value eg.949246851
5) Selection of the row raises error
SQLSTATE[22003]: Numeric value out of range: 7 ERROR: value "949246851" is out of range 

lastInsertId documentation contains...

Returns the ID of the last inserted row, or the last value from a sequence object, depending on the underlying driver. For example, PDO_PGSQL requires you to specify the name of a sequence object for the name parameter.

**Comment by dg** [comment]
If this issue is still valid, please open it again in https://github.com/nette/database
