### ISSUE TITLE
Requirements-Checker: Zkouška mod_rewrite na základě prostředí / feature

### ISSUE THREAD

**Issue by kubinpetr** [nette/nette#1518]
Navrhuji přidat podmínku, kdy se zkontroluje prostřední (nginx, ... apache .....) a jen v případě, když se jedná o apache se bude zkoušet mod_rewrite.

Jak je vidět v tomto postu, je to pro některé matoucí:
http://forum.nette.org/cs/20606-prechod-z-apache-na-nginx#p149239

**Comment by fprochazka** [comment]
:+1: pošleš pullrequest prosím?

**Comment by kubinpetr** [comment]
Tak jsem to zkusil, ale nevím, zda to je v pořádku pro nette oko.
Pokud ne, tak sorry, alespon jsem to zkusil.
#1519

**Comment by dg** [comment]
To se mi nelíbí. Ty hlášky jsou sice zavádějící, ale skrýt je není řešení. Spíš opravit text.

**Comment by f3l1x** [comment]
Nebylo by spatne mit requirements checker jako vlastni repo. Nenasel jsem zpusob jak si ho pullnout samostatne.
