### ISSUE TITLE
Minified version of Nette 2.3.0-beta do not work

### ISSUE THREAD

**Issue by bckp** [nette/nette#1522]
If you try use minified version of Nette 2.3.0-beta on sandbox, it came with errors, not able to create container.

**Notice:**
User Notice
Type of service 'tracy.blueScreen' is unknown

**Exception:**
Nette\DI\ServiceCreationException
Service 'application.application': Reference to missing service of type Tracy\Bar.

If I change Minified version for Composer one, all works as expected.

**Comment by dg** [comment]
It works for me.

Do you use some opcode cache?

**Comment by bckp** [comment]
Opcode is disabled in my Apache configuration, just tried that on server, same result...

Mám zkusit někam nahrát ZIP s celým sandboxem, který u mě nefunguje?

**Comment by dg** [comment]
I believe we both have the same zip with the same sandbox.

**Comment by bckp** [comment]
If I truncate vendor dir, and put only nette.phar in it, it will broke sandbox, if all files remain, only add nette.phar, and change bootstrap.php to require nette.phar instead of autoload.php, all work as expected...

**Comment by dg** [comment]
I confirm bug in minifier.

**Comment by dg** [comment]
Fixed https://github.com/nette/nette/releases/tag/v2.3.0-beta

**Comment by bckp** [comment]
@dg , reopen pls... new issue: 

Nette\MemberAccessException
Call to undefined method Nette\DI\Statement::setEntity()

Only on minified again, normal version works good.

**Comment by dg** [comment]
Uff, now it is ok. I hope.

**Comment by bckp** [comment]
@dg confirmed, works :+1:

**Comment by dg** [comment]
:tada:
