### ISSUE TITLE
Segmentation fault after submitting a form

### ISSUE THREAD

**Issue by H0w4rd** [nette/nette#1524]
My project doesn't work with 2.3.0 because of an error:

[Mon Mar 02 13:59:05.884320 2015] [core:notice] [pid 3691] AH00052: child pid 15391 exit signal Segmentation fault (11)

after submitting a form, the method for saving the form is not called, browser says ‘Connection interrupted’, nothing in log directory, no tracy shown.
Problem with both PHP 5.5.15 and 5.6.5.

It works with Nette 2.2.7.

**Comment by JanTvrdik** [comment]
Unless you tell us what is causing the segfault there is very little we can do for you.

**Comment by H0w4rd** [comment]
I would like to provide more details. How can I find the problematic place in the Nette code? 
There is no problem in my code, there is a form with some textboxes and a submit button, there is a form success definition:
$form->onSuccess[] = $this->formSubmitted;
but the method formSubmitted() is never called, it crashes somewhere after the code which creates the form and before onSuccess method.

**Comment by dg** [comment]
There are two related (maybe) differencies:
- https://github.com/nette/forms/commit/903a0b97d13e4c898494e7017615cc6c261a6b94
- https://github.com/nette/utils/commit/50dbab6989f280d1433a360dc8cde8c470c85793#diff-1977cb1ac7943200a46bb0af12dec50b

**Comment by H0w4rd** [comment]
Thank you.   Forms/Container.php:

	public function validate(array $controls = NULL)
	{ 
	    die("A");
		foreach ($controls === NULL ? $this->getComponents() : $controls as $control) {
			$control->validate();
		}
		die("B");
                ...

If I comment die("A"),  the following die("B") is not performed.

**Comment by dg** [comment]
Can you check on which control the validate() fails? Or is it on getComponents()?

**Comment by H0w4rd** [comment]
getComponents() is ok
I did this:
	    //die("A");
		foreach ($controls === NULL ? $this->getComponents() : $controls as $control) {
		    file_put_contents(__DIR__ . "/../../../../../temp/nnn.txt", "|".$control->name, FILE_APPEND);
			$control->validate();
		}
		die("B");

File nnn.txt contains: |payment_date|payment_date|payment_date|payment_date|payment_date|payment_date|payment_date
payment_date is the first field in the form
Type of this field is: Vodacek\Forms\Controls\DateInput
So I suppose Vodacek's DateInput is not compatible with Nette 2.3.0. Or could be the problem in Nette?

**Comment by milo** [comment]
@H0w4rd How you add `payment_date` component into form? Which rules do you set on it?

**Comment by H0w4rd** [comment]
This is how payment date is created:
$input = $form->addDate("payment_date", "Datum platby", \Vodacek\Forms\Controls\DateInput::TYPE_DATETIME);
Just one rule:
$input->addRule(Form:VALID, "%label musí obsahovat datum ve formátu 'den.měsíc.rok hodina:minuta:sekunda'.", NULL);

Rendered as (with jquery alterations):
<input id="frm-form-form-payment_date" class="form-control text hasDatepicker" type="text" value="2015-02-23T15:31:00Europe/Prague" data-nette-rules="[{"op":":filled","rules":[{"op":":valid","msg":"Datum platby…íc.rok hodina:minuta:sekunda'."}],"control":"payment_date"}]" data-dateinput-type="datetime"></input>
<input class="form-control text" type="hidden" value="2015-02-23T15:31:00Z" name="payment_date" style="cursor: pointer;"></input>

I tried to change TYPE_DATETIME to TYPE_DATE and there is the same problem.
I tried to change addDate to addText and it works.

**Comment by milo** [comment]
Cannot reproduce it. Without JavaScript. Tried with:
```
# composer.json
"nette/nette": "~2.3.0", 
"voda/date-input": "~1.0" 
```

```php
# HomepagePresenter.php
<?php

namespace App\Presenters;

class HomepagePresenter extends BasePresenter
{
	public function startup()
	{
		parent::startup();
		\Vodacek\Forms\Controls\DateInput::register();
	}

	
	public function createComponentForm()
	{
		$form = new \Nette\Application\UI\Form;
		
		$input = $form->addDate("payment_date", "Datum platby", \Vodacek\Forms\Controls\DateInput::TYPE_DATETIME);
		$input->addRule($form::VALID, "%label musí obsahovat datum ve formátu 'den.měsíc.rok hodina:minuta:sekunda'.", NULL);
		
		$form->addSubmit('send');
		
		$form->onSuccess[] = $this->formSuccess;
		
		return $form; 
	}
	
	public function formSuccess($form)
	{
		dump($form);
	}
}
```

```latte
# default.latte
{block content}

{control form}
```

The `2015-02-23T15:31:00Europe/Prague` pass and dump is done.

**Comment by H0w4rd** [comment]
Well then, It's up to me to prepare a failing example, I suppose.

**Comment by milo** [comment]
Failing fandbox would be great!

**Comment by H0w4rd** [comment]
Sorry about my late reply. Failing sandbox is ready. How can I deliver it to you?

**Comment by dg** [comment]
Of course.

**Comment by H0w4rd** [comment]
You can download it here: http://uloz.to/xcv8yzUb/test-7z
Password: fdssdffds654

It contains only one presenter and one action, I deleted all unnecessary things.

Go to URL:  /payment/add
Fill all fields and submit the form. The method saveForm() in app/component/Payment/PaymentForm.php should be called, but it's not because of segfault.
It's OK with Nette 2.2.x.
If you change the type of the first item (vodacek's dateinput) to normal textbox, it works (you can do it in app/Model/PaymentRepository.php - search TYPE_DATETIME and change it to TYPE_TEXT).

I noticed Nette 2.3.1 has been released, I tried it, but nothing changed, still segfaults.

**Comment by matej21** [comment]
there is a bug in your code which causes infinite recursion.

in `\RTsoft\Component\GridForm\FormComponent` on lines 135 and 140, replace `Form::VALID` with `'\Vodacek\Forms\Controls\DateInput' . '::validateDateInputValid'`

**Comment by H0w4rd** [comment]
Thank you very much and I'm sorry I was bothering you with this. My code worked with Nette 2.0, 2.1, 2.2, that's why I considered it as a nette bug.
I've installed xdebug package and now I can see that error message too.
