### ISSUE TITLE
Nette tutorial failed in SignInForm

### ISSUE THREAD

**Issue by taylorren** [nette/nette#1526]
Followed the description on: http://doc.nette.org/en/2.3/quickstart/authentication and failed in the following particular method:

    class SignPresenter extends BasePresenter
    {

        /** @var SignFormFactory @inject */
        public $factory;

    /**
     * Sign-in form factory.
     * @return Nette\Application\UI\Form
     */
        protected function createComponentSignInForm()
        {
            $form = new Form;
            $form->addText('username', 'Username:')
                    ->setRequired('Please enter your username.');

![ashampoo_snap_2015 04 12_18h01m39s_002_](https://cloud.githubusercontent.com/assets/3853711/7105173/0250ba06-e13e-11e4-8b6c-87ad20c7706e.png)

Am I missing something?

**Comment by keltuo** [comment]
use Nette\Application\UI\Form;

On line 25: you have to use namespace of class, like this
"$form = new \Nette\Application\UI\Form();"
