### ISSUE TITLE
\Nette\Security\User::login() - authentication should be before logout

### ISSUE THREAD

**Issue by DanielNoga** [nette/nette#1527]
Reproduce:
1) I am logged in
2) I try loginIn with new credentials and I use wrong credentials

Current result:
My previous user was logout

Expected:
My previous user was still logged

Move line 
"$this->logout();" 
after 
"$id = $this->getAuthenticator()->authenticate(func_get_args());" 
should fix it

**Comment by legendik** [comment]
I think better way is disallow login page for logged in users and redirect to homepage with flashMessage for example.

**Comment by DanielNoga** [comment]
In our application we are using virtual temporary user. So we have an logged user which should be unlogged after successful new login.

**Comment by dg** [comment]
I think that current behavior is correct.
