### ISSUE TITLE
Flash message and redirect

### ISSUE THREAD

**Issue by Zemistr** [nette/nette#1529]
I have this code:

```php
<?php
namespace App\Modules\BackModule\Presenter;

class SignPresenter extends BasePresenter {
	public function actionOut() {
		$this->user->logout();
		$this->flashMessage('message.info.signed_out', 'info');
		// $this->redirect('in');
	}
}
```

Without redirect is everything OK and I see the message.
But, if I use ```$this->redirect('in');```, message is not showed.

**Comment by zrnecx** [comment]
i am using $this->flashMessage("msg"); and it works fine..

2015-04-20 12:36 GMT+02:00 Martin Zeman <notifications@github.com>:

**Comment by Zemistr** [comment]
And with `$this->redirect('...');` ? :)

**Comment by Zemistr** [comment]
Fixed! :smile: 

Never ever use `$this->template->something = something` in `injectMethod`! :sweat_smile:
