### ISSUE TITLE
Allow gitter integration

### ISSUE THREAD

**Issue by fprochazka** [nette/nette#1533]
@dg do you think you could allow the integration for nette/nette room and then copy the hooks to other repos so we have a stream of related events in the room? 

It posts the info in the right panel nicely.
![snimek obrazovky porizeny 2015-06-28 18 11 11](https://cloud.githubusercontent.com/assets/158625/8397147/d264477a-1dc1-11e5-8d8c-910bbd7d4586.png)

And can be enabled easily for all `nette/*` repos.

![snimek obrazovky porizeny 2015-06-28 18 18 27](https://cloud.githubusercontent.com/assets/158625/8397154/1d662be4-1dc2-11e5-8b7c-d5e2971ef8e9.png)

At least pullrq and issue open/close would be nice. Comments could be also added, so we can see if anything is happening in nette org.

**Comment by dg** [comment]
Done

**Comment by fprochazka** [comment]
:+1: thanks!

**Comment by fprochazka** [comment]
@dg haven't you added it twice by accident?

**Comment by dg** [comment]
Once for nette/nette and once for nette/nette/cs. I'll check it.

**Comment by dg** [comment]
test

**Comment by dg** [comment]
test22
