### ISSUE TITLE
Finder::find() - Filtr callback se zavolá jen na složky

### ISSUE THREAD

**Issue by bendovercz** [nette/nette#1534]
Ahoj, dnes jsem narazil na problém s Finderem. Pokud hledám složky i soubory a chci na ně aplikovat filter(), tak jeho callback se zavolá jen u složek.

``` php
Nette\Utils\Finder::find('*')->in('/data/files/')->filter(function($file) {
	# Tento callback odfiltruje jen složky
	return false;
});
```

Používám Nette 2.3.3.

**Comment by dg** [comment]
Zkus zavolat `filter` před `in`.

**Comment by bendovercz** [comment]
@dg Tak to pro změnu vyfiltruje pouze soubory.

**Comment by dg** [comment]
Ano, první je pro soubory a druhý pro adresáři.
