### ISSUE TITLE
Nette\Utils\Strings::toAscii doesnt convert &#227; to ascii character

### ISSUE THREAD

**Issue by reflexator** [nette/nette#1535]
Example: jo&amp;#227;o-marques
Results: jo&#227;o-marques
Correct result: joao-marques

**Comment by xificurk** [comment]
@reflexator I'm kind of confused - what are you passing to toAscii method? Text 'jo&#227;o-marques' is already in ASCII, so `Strings::toAscii()` will leave it unchanged.

**Comment by reflexator** [comment]
So it will not remove diacritic as it says in documentation?

I am little bit comfused

```
echo Strings::toAscii('žluťoučký kůň'); // zlutoucky kun
```

**Comment by reflexator** [comment]
So it looks that it will remove diacritics if you pass string in ASCII, but if you pass in numeric character reference it doesnt remove it.

**Comment by xificurk** [comment]
@reflexator Yes, it will remove diacritics. You did not answered the question - what are you passing to toAscii method? If the answer is 'jo&#227;o-marques', then there is nothing to remove, there is no diacritics in that text.

(I'm sorry, I've copied over a wrong line in the previous post.)

**Comment by reflexator** [comment]
Yeah I am passing string with numeric reference, my bad, I will close ticket.
