### ISSUE TITLE
Z HTTP Requestu nelze získat "?"

### ISSUE THREAD

**Issue by jasin755** [nette/nette#1536]
Neexistuje možnost jak z objektu httpRequest získat celou request uri např. pokud bych chtěl kanonizovat url www.web.cz/? na www.web.cz/

**Comment by milo** [comment]
Use english, please.

Correct repository for this issue is [nette/http](https://github.com/nette/http). From `httpRequest` you can get [Url](https://github.com/nette/http/blob/0d9ef49051fba799148ef877dd32928a68731766/src/Http/Url.php) by `getUrl()` method.
