### ISSUE TITLE
Requirements Checker => PHP version isnt controled

### ISSUE THREAD

**Issue by janfiedler** [nette/nette#1538]
Hi,
i download Nette-2.3.5 on page isnt information about need PHP 5.4.4. I uses included Requirements Checker and passed good PHP version	5.3.3-7+squeeze19 green checker. But my app stop working. After i took look deeper i see i must have 5.4.4.

**Comment by dg** [comment]
Nette 2.3 requires PHP 5.3.1

**Comment by janfiedler** [comment]
On PHP 5.3.3 with nette 2.3.5 i get error in this part of new code:

			if (!isset($this->structure['hasMany'][$table])) {
				return [];
			}
			return $this->structure['hasMany'][$table];

something about 'return['

But now after i try it again (git pull on my server) now it is working without error. Sorry for mistake with this issue.

**Comment by janfiedler** [comment]
Back on horse,
i know where was problem.
It is all about commit from this day:
https://github.com/nette/database/pull/93/commits

I copy all row code, not only changes and here was: return [];
Repair in 93 is working, but is used maybe in bad raw file?

**Comment by dg** [comment]
Now is it ok?

**Comment by janfiedler** [comment]
No, isnt.
Take look to pulled Structure.php
https://github.com/Unlink/database/blob/87a60dcb7857012cd6c297be544d76d28f2da003/src/Database/Structure.php

Here is wrong array defined:
			if (!isset($this->structure['hasMany'][$table])) {
				return [];
			}
			return $this->structure['hasMany'][$table];

In original file for Nette 2.3.5 is:
			if (!isset($this->structure['hasMany'][$table])) {
				return array();
			}
			return $this->structure['hasMany'][$table];

This make required higgher PHP than 5.3. because shorten array in [] is only in 5.4+

**Comment by dg** [comment]
Master requires PHP 5.6, Nette 2.3 requires PHP 5.3, see this file https://github.com/nette/database/blob/v2.3/src/Database/Structure.php

**Comment by janfiedler** [comment]
It is make sense.
This is new information for me, sorry so much for loosing your time and thank you. So its all ok now.

**Comment by dg** [comment]
No problem :-)
