### ISSUE TITLE
js email validation freeze browser

### ISSUE THREAD

**Issue by syky01** [nette/nette#1540]
Steps to reproduce:
```php
$form = new Form;
$form->addText('email', 'Email:')
  ->addRule(Form::FILLED, 'Zadejte email')
  ->addRule(Form::EMAIL, 'Email nemá správný formát');
$form->addSubmit('send', 'Odeslat');
$this->template->form = $form;
```
paste to input, click to submit:
`"><img src=x onerror=prompt(document.domain)>`

result: 
freeze browser tab

**Comment by dg** [comment]
Which browser?

**Comment by syky01** [comment]
Google Chrome	45.0.2454.101
Firefox 40.0.3
Internet explorer 11
(windows versions)

**Comment by syky01** [comment]
Updated (freeze after validation) must click to submit
