### ISSUE TITLE
Version 2.3.9

### ISSUE THREAD

**Issue by remicollet** [nette/nette#1544]
FYI, it seems this version is already referenced on packagist, when obviously broken (requires all @dev), and the tag have been removed.

https://packagist.org/packages/nette/nette

**Comment by dg** [comment]
Thanks for the warning!

I created a draft of release note in Releases and GitHub automatically created tag on master branch :-/ That's annoying.

![2016-01-20_13-38-57](https://cloud.githubusercontent.com/assets/194960/12449144/7ee472a8-bf7b-11e5-9491-2a977f09d82e.png)

**Comment by remicollet** [comment]
Thanks.

Is a 2.3.9 still planed ?

**Comment by dg** [comment]
Yes, in few days.
