### ISSUE TITLE
Server global variable is not checked for faked data in RequestFactory

### ISSUE THREAD

**Issue by howkey666** [nette/nette#1547]
Hi,
i found, that global variable `$_SERVER['HTTP_X_FORWARDED_FOR']` is not checked for faked data in https://api.nette.org/2.3.9/source-Http.RequestFactory.php.html#203
For exmaple use Firefox with X-Forwarded-For Header addon (https://addons.mozilla.org/en-US/firefox/addon/x-forwarded-for-header/) and set IP Address to "kokos". Then run this part of code:
```
$factory = new \Nette\Http\RequestFactory();
var_dump($factory->createHttpRequest());
```

You will see in output this:
```
...
["x-forwarded-for"]=>
    string(5) "kokos"
...
```

Suggested fix is to call `filter_var($address, FILTER_VALIDATE_IP)` for each IP in `$_SERVER['HTTP_X_FORWARDED_FOR']`. I can prepare PR with fix, but now I do not have a time.

**Comment by dg** [comment]
It should be fixed here https://github.com/nette/http/issues/87, can you test it?

**Comment by howkey666** [comment]
Yes, you are right. :) Sorry, I should look directly to HTTP issues before posting this one. Thanks!
