### ISSUE TITLE
Callback() in search field on nette.org generates wrong URL

### ISSUE THREAD

**Issue by vohratom** [nette/nette#1549]
when you try to find 

> callback()

in the search field on www.nette.org, you are redirected to the wrong URL 

> https://api.nette.org/2/function-callback...html

What is wrong? 
Three dots in the end.

Expected?
.html not ...html

**Comment by f3l1x** [comment]
It works at latest version: https://api.nette.org/2.4/function-callback.html

I think we can close it.

**Comment by vohratom** [comment]
Fix verified, but idk how to close it :)) do you know? Or only the owner can close it?
