### ISSUE TITLE
Email validator

### ISSUE THREAD

**Issue by jedlirad** [nette/nette#1550]
Validators::isEmail(’petr@skᬡ1898.cz’) vraci true.. ten divnej znak je takovej ctverecek s otaznickem.. viz obrazek,
![screen shot 2016-11-14 at 13 24 16](https://cloud.githubusercontent.com/assets/8957073/20264904/1e1fc560-aa6e-11e6-84c7-e507dec5c06d.png)

**Comment by JanTvrdik** [comment]
If it returns TRUE, the email is likely valid. Why do use assume otherwise? Also this should be reported to to nette/utils issue tracker.

**Comment by jedlirad** [comment]
OK, If you think its valid domain delete this issue...gl

**Comment by uestla** [comment]
The arrogance is strong with this one...

**Comment by milo** [comment]
@jedlirad That 'strange' char is not a question mark in square. Question mark means that your font's character set cannot display it.

The character is 3-byte lenght in UTF-8 `E1 AC A1` AND 2-byte length in UTF-16 `1B 21`.

So, actually the domain is valid domain name by IDN-2008 (http://www.unicode.org/cldr/utility/idna.jsp?a=sk%E1%AC%A11898.cz)
