### ISSUE TITLE
MSSQL update query problem

### ISSUE THREAD

**Issue by internetovaskola** [nette/nette#1551]
Nette 2.4 and MSSQL update query is generated with following problem:

`UPDATE [app_users] SET (...columns...) WHERE ([id] = '1')`

right is:

`UPDATE [app_users] SET ...columns... WHERE ([id] = '1') //Without parenthesis`

Thanks a lot!

**Comment by dg** [comment]
Write exactly the php code you use.

**Comment by internetovaskola** [comment]
For example this:
```
// Update query
            try {
                $this->context->table(self::TABLE_NAME)
                    ->where(self::TABLE_ID, $data->id)
                    ->update(array($columns));
            } catch (\PDOException $ex) {
                throw new \PDOException('Unable to update user data.');
            }
```

**Comment by dg** [comment]
Try change ` ->update(array($columns));` to ` ->update($columns);`

**Comment by internetovaskola** [comment]
You have truth. It works. Stupid donkey think. Thank you very much. Please, delete this thread, Its my issue.
