### ISSUE TITLE
Can not get values on onValidate when form is not valid

### ISSUE THREAD

**Issue by japlavaren** [nette/nette#1554]
hi,

based on new [nette release](https://github.com/nette/forms/releases/tag/v3.1.0) **Form::onValidate - values are passed only when form is valid**.

But in my opinion [current implementation](https://github.com/nette/forms/blob/master/src/Forms/Container.php#L199) is wrong:
```
$isValid = !$this->getErrors();
foreach ($this->onValidate as $handler) {
	$params = Nette\Utils\Callback::toReflection($handler)->getParameters();
	$types = array_map([Nette\Utils\Reflection::class, 'getParameterType'], $params);
	$handler(
		!isset($types[0]) || $this instanceof $types[0]
			? $this
			: ($isValid ? $this->getValues($types[0]) : null),
		isset($params[1]) && $isValid
			? $this->getValues($types[1])
			: null
	);
}
```
variable `$isValid` is loaded just at the beginning so when first validation fails, loop in container does not know about this and tries to pass values to second validation handler, what [is causing warning](https://github.com/nette/forms/blob/master/src/Forms/Container.php#L113)

So correct implementation should be
```
foreach ($this->onValidate as $handler) {
	$isValid = !$this->getErrors();
	$params = Nette\Utils\Callback::toReflection($handler)->getParameters();
	$types = array_map([Nette\Utils\Reflection::class, 'getParameterType'], $params);
	$handler(
		!isset($types[0]) || $this instanceof $types[0]
			? $this
			: ($isValid ? $this->getValues($types[0]) : null),
		isset($params[1]) && $isValid
			? $this->getValues($types[1])
			: null
	);
}
```

**Comment by dg** [comment]
Behavior restored in v3.1.2
