### ISSUE TITLE
nette/nette v3.1.1 requires nette/tokenizer (^3.0)

### ISSUE THREAD

**Issue by j-nicolas** [nette/nette#1555]
nette/tokenizer is said to be abandoned.
composer refuses to remove nette/tokenizer.
composer why nette/tokenizer :
nette/nette v3.1.1 requires nette/tokenizer (^3.0)

best regards and many thanks for all!

**Comment by dg** [comment]
Yes, the tokenizer will be removed in the next version of nette/nette.
