### ISSUE TITLE
New snippets do not respect template rendering code

### ISSUE THREAD

**Issue by ondrejmirtes** [nette/nette#160]
If I pass some arguments to $control->render() or if I render Control with a different method than render(), new snippets still try to call render() method without any parameters.

For example, if I have this code in template:

{control rating $trip->rating}

And this component has some snippets in it and they are invalidated in AJAX request, the component is still rendered via calling $control->render() in LatteMacros.php, line 1228.

**Comment by peldax** [comment]
@hrach Ahoj, prosím o zápis do dokumentace. Teď jsem hledal proč se mi při AJAXu nepředává parametr a ejhle, najdu issue z roku 2010.
