### ISSUE TITLE
Latte nepředává interní $_form do vkládaných šablon.

### ISSUE THREAD

**Issue by MartinStepar** [nette/nette#536]
V první šabloně pomocí makra `{form jmenoFormulare}` začnu kreslit formulář. Uprostřed pro některé vlastní typy políček vkládám speciální šablony pomocí `{include @jmenoSablony.latte form => $form}`. Uvnitř této šablony ale vykreslení prvků makry `label` a `input` selže, protože si Latte nepředalo interní proměnnou `$_form`. Někdy během vývoje verze 2 to ještě fungovalo, tipuji, že se dříve používala proměnná `$form`.

Verze Nette: dev 4e4312d.

**Comment by dg** [comment]
@MartinStepar please open it again in https://github.com/nette/forms
