### ISSUE TITLE
Cache::ALL alwayes deletes whole cache, even when called over namespace

### ISSUE THREAD

**Issue by janlanger** [nette/nette#592]
Example:

    $cache = new Cache($cacheStorage,'namespace');
    $cache->clean(array(Cache::ALL=>true));

result: whole cache was deleted

expected: only part of cache in "namespace" was deleted

Same issue has already few thread on forum [CZ]:
http://forum.nette.org/cs/7305-cache-clean-nemaze-len-svoj-namespace
http://forum.nette.org/cs/2309-cache-clean-jak-smazat-vsechny-data-v-urcite-namespace
http://forum.nette.org/cs/3145-nette-caching-cache-clean-mazat-pouze-namespace

**Comment by lukyer** [comment]
Really annoying undocumented bug. Cleaning cache on namespace really SHOULD clean only its namespace. No documentation / phpdoc / nothing. :-1:

**Comment by racinmat** [comment]
Please, anyone, fix this. I really like the suggestion with new tag Cache::NAMESPACE.

**Comment by milo** [comment]
Imho, this is a lot of work to do it properly. One have to find all items in namespace across the whole cache. It is an expensive operation.

One nasty hack is auto-tagging, but it is a big BC break.

Btw. solution exists. Tag all items in namespace and clean them by tag.

**Comment by dg** [comment]
Moved to https://github.com/nette/caching/issues/40
