### ISSUE TITLE
Nette\Database - escaping

### ISSUE THREAD

**Issue by ghost** [nette/nette#819]
Code: $this->database->table('table')->select("DATE_FORMAT(time '%b %d %Y %h:%i %p'   ) AS date);

generates SQL:  SELECT DATE_FORMAT(`time`, '%`b` %`d` %Y %`h`:%`i` %`p`') AS `date`
FROM `table`

As seen, delimiters ` are added with no sense. Note that they are added only to small letters, not capitals (%Y works well, %d not).

I hope this is a good way how to announce a bug, If not, feel free to remove this post.

Submitted to forum: http://forum.nette.org/cs/10485-nette-database-vklada-nadbytecne-mysqli-escapovatko

**Comment by milo** [comment]
Seems correct to me pass format string as an argument. This can be solved by:
```
$db->table('table')->select("DATE_FORMAT(time, ?) AS date", '%b %d %Y %h:%i %p')
```

Proposed to close?
