### ISSUE TITLE
Nette\Latte\Parser: parseMacroTag() - wrong parsing macro: {_x_ "whatever"} and similar with "_" prefix in macro

### ISSUE THREAD

**Issue by j3nda** [nette/nette#992]
hello,

IMHO: i found a bug with {_whatever} macro, see below:

i have file: @layout.latte - with this 2x macros:
```
{_"whatever"}
{_x_ "abc"}
```

and in BasePresenter:
```php
public function templatePrepareFilters($template)
	$latte = $this->getPresenter()->getContext()->nette->createLatte();
	$template->registerFilter($latte);
	
	$set  = \s2\templating\macros\CoreMacros::install($latte->compiler);
	
	// the code in array($me, macroXXX) is not important at this point.
	// IMPORTANT is only {_x_ ...} and {_whatever ...} as user-defined macro

	$me->addMacro('_x_',       array($me, 'macroXXX'), array($me, 'macroXXX'));
	$me->addMacro('_whatever', array($me, 'macroXXX'), array($me, 'macroXXX'));	
}
```

- - -

{_"whatever"} --> OK: through: $template->translate()

{_x_ "abc"} --> FAILS: parseMacroTag(): returns from Strings::match(): it returns (@see below): $template->translate(_ "abc"); // and in this point is parse error.

dump($match) on line: 357 (file: Parser.php) return this:
```
array(13) {
   0 => "_x_ "abc"" (9)
   1 => "_"
   name => "_"
   2 => ""
   noescape => ""
   3 => ""
   shortname => "_"
   4 => "_"
   args => "x_ "abc"" (8)
   5 => "x_ "abc"" (8)
   modifiers => "|escape" (7)
   6 => ""
   7 => ""
}
```
and this is wrong, because macro is "_x_" whole text and parser split into: "_" and "x_" and "abc" as args.

it's similar to use anything with prefix "_" as macro, ex: {_mymacro ...}, {_whatever ...}, ...
i'm not guru in REGEX, but i think, that regex have some bugs: 
the original:
```
$match = Strings::match($tag, '~^
	(
		(?P<name>\?|/?[a-z]\w*+(?:[.:]\w+)*+(?!::|\())|   ## ?, name, /name, but not function( or class::
		(?P<noescape>!?)(?P<shortname>/?[=\~#%^&_]?)      ## !expression, !=expression, ...
	)(?P<args>.*?)
	(?P<modifiers>\|[a-z](?:'.Parser::RE_STRING.'|[^\'"])*)?
()\z~isx');
```
- - -
IMHO:

(maybe it would be better to handle first all user-defined macros with prefix "_" and then translation macro {_}, from: http://doc.nette.org/cs/default-macros ~ {_}Text{/_}; {_expression}; {!_expression}

MY POINT OF VIEW is, that i can't addMacro like this: "__" to some override gettext functionality only for templates. my typical usage is: {__ myTag} or {__ "whatever"}
)

**Comment by dg** [comment]
It is just limitation of Latte…
